### ISSUE TITLE
How to writen migrations?

### ISSUE THREAD

**Issue by prefect1** [natanfelles/codeigniter-migrate#2]
Interested in the question how to write a insert $data into the generated migrator the table.
When insert the following code migrator refuses to work giving the error something is wrong:
// Dumping data for table 'groups'
		$data = array(
			array(
				'id' => '1',
				'name' => 'admin',
				'description' => 'Administrator'
			),
			array(
				'id' => '2',
				'name' => 'members',
				'description' => 'General User'
			)
		);
		$this->db->insert_batch('groups', $data);

**Comment by natanfelles** [comment]
https://codeigniter.com/user_guide/libraries/migration.html#create-a-migration
