### ISSUE TITLE
Use multiple databases

### ISSUE THREAD

**Issue by federicovilla** [natanfelles/codeigniter-migrate#3]
Thanks a lot for the great and useful script.
Since in my web site there are multiple databases and I need to migrate not the default DB I'm wondering how can I config dbforge to do so...I didn't find any useful resource on the web, even if this would be a great feature.
Is it possible to implement this in your project?
Thanks a lot

**Comment by natanfelles** [comment]
Yes. Great idea.

To add a way to change the dbgroup name in the frontend. A dropdown with existing dbgroups could solve this issue.

**Comment by federicovilla** [comment]
Thanks for feedback natanfelles.
Great idea about dropdown.
